const ActionTypes = {
  // User
  FETCH_USER_DETAILS_REQUESTED: 'FETCH_USER_DETAILS_REQUESTED',
  FETCH_USER_DETAILS_SUCCEEDED: 'FETCH_USER_DETAILS_SUCCEEDED',
  FETCH_USER_DETAILS_FAILURE: 'FETCH_USER_DETAILS_FAILURE'
};

export default ActionTypes;
