const ActionTypes = {
  // Auth
  SET_AUTHENTICATION: 'SET_AUTHENTICATION',
  // User
  FETCH_LOGIN_DETAILS_REQUESTED: 'FETCH_LOGIN_DETAILS_REQUESTED',
  FETCH_LOGIN_DETAILS_SUCCEEDED: 'FETCH_LOGIN_DETAILS_SUCCEEDED',
  FETCH_LOGIN_DETAILS_FAILURE: 'FETCH_LOGIN_DETAILS_FAILURE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_USER_PROFILE_SUCCEEDED: 'UPDATE_USER_PROFILE_SUCCEEDED',
  USER_LOGOUT: 'USER_LOGOUT',

  // Items
  ITEMS_DIALOG_OPEN: 'ITEMS_DIALOG_OPEN',
  ITEMS_DIALOG_CLOSE: 'ITEMS_DIALOG_CLOSE',
  FETCH_ALL_ITEMS_SUCCEEDED: 'FETCH_ALL_ITEMS_SUCCEEDED',
  FETCH_ALL_ITEMS_FAILURE: 'FETCH_ALL_ITEMS_FAILURE',
  SET_SELECTED_ITEM: 'SET_SELECTED_ITEM'
};

export default ActionTypes;
