const ActionTypes = {
  // Auth
  SET_AUTHENTICATION: "SET_AUTHENTICATION",
  // User
  FETCH_LOGIN_DETAILS_REQUESTED: "FETCH_LOGIN_DETAILS_REQUESTED",
  FETCH_LOGIN_DETAILS_SUCCEEDED: "FETCH_LOGIN_DETAILS_SUCCEEDED",
  FETCH_LOGIN_DETAILS_FAILURE: "FETCH_LOGIN_DETAILS_FAILURE",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  USER_LOGOUT: "USER_LOGOUT"
};

export default ActionTypes;
